### ISSUE TITLE
More-spec calculation error

### ISSUE THREAD

**Issue by alarig** [nttgin/BGPalerter#1]
Hi,

I just tested the tool by hijacking myself, it works. But it detects a more-spec that is another prefix.

```
2019-08-14T15:43:26.671Z [production] verbose: Possible change of configuration. A new prefix 2a00:5884::/32 is announced by AS204092. It is a more specific of 2a0e:f40::/29 (Grifon).
```

This prefix is correctly announced and configured:
```yaml
2a00:5884::/32:
  description: Grifon
  asn: 204092
  ignoreMorespecifics: false
```

Plus, it’s not a more specific of 2a0e:f40::/29.
