### ISSUE TITLE
Hot reloading of configuration

### ISSUE THREAD

**Issue by DamianZaremba** [nttgin/BGPalerter#103]
**Describe what you would like to achieve**
Currently the configuration is only read on startup, changing the monitored prefixes requires restarting the instance.

In an environment which has many prefix monitors, the configuration of which change in a relatively dynamic manner this requires restarting the process very regularly (hourly/daily) interval.

**Describe why the current solution (if any) is not satisfactory**
1. During the process restart any RIS messages are lost, potentially causing missed messages
2. alarmOnlyOnce only applies during the single run, causing messages to re-trigger at the restart interval
3. notificationIntervalSeconds only applies during the single run, causing messages to re-trigger at the smaller of notificationIntervalSeconds and the restart interval

**Provide an example**
Start the instance with a prefixes.yml;
```
23.235.32.0/24:
    asn: [54113]
    description:  example prefix 1
    ignore: false
    ignoreMorespecifics: false
```
Once running update prefixes.yml;
```
23.235.32.0/24:
    asn: [54113]
    description:  example prefix 2
    ignore: false
    ignoreMorespecifics: false

23.235.36.0/24:
    asn: [54113]
    description:  example more specific prefix
    ignore: false
    ignoreMorespecifics: false
```

No new prefixes will be subscribed to, any withdrawals, announcements etc will not be notified.

**Your information**
@DamianZaremba, Fastly / Infra Bits
