### ISSUE TITLE
monitorASns doesn't generate alerts

### ISSUE THREAD

**Issue by captainark** [nttgin/BGPalerter#1089]
**Describe the bug**

No matter how I try and configure it, I can't get the `monitorASns` option to generate alerts when an upstream not declared in the list exists.

**Provide an example**

I've voluntarily removed one of our upstreams (8218) from the configuration to try and generate an alert, as follows:

```
options:
  monitorASns:
    '20756':
      group: noc
      upstreams:
        - 174
      downstreams: null
```

I also have `thresholdMinPeers` at `1` for `monitorPathNeighbors`.

I can provide the full configuration file if that could help.

**Expected behavior**

I would expect an alert to be generated, since the upstream list doesn't match what is declared in the configuration.

**Are you using the binary or the source code?**

I'm using v1.32.0 downloaded from the release page of the GitHub project.

**Your information**

AS20756 & AS209510 - Nameshield
