### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jayeshkumarbhoi** [nttgin/BGPalerter#1181]
**Describe the bug**

I am currently using the latest BGPAlerter version (1.32.0) with the latest 'config.yml' file in which only the Slack channels option is enabled to post alerts. However, I've noticed that after 15 minutes, it consumes all the memory limit allowed to it and crashes. To address this issue, I doubled the memory limit, and this time it runs for 4 hours and crashing again with the same error. This led me to suspect that the Node.js application's code may have potential memory leaks or inefficiencies. The strange part is that if I use an older 'config.yml' file (from the 1.29 release), this problem disappear. see below logs
 

```
<--- Last few GCs --->

[70:0x7fa67e593010]   945326 ms: Scavenge (reduce) 496.2 (507.3) -> 496.1 (508.3) MB, 11.0 / 0.0 ms  (average mu = 0.872, current mu = 0.632) allocation failure;
[70:0x7fa67e593010]   949133 ms: Mark-sweep (reduce) 497.0 (508.3) -> 496.8 (509.1) MB, 3334.4 / 0.0 ms  (+ 207.2 ms in 15 steps since start of marking, biggest step 94.2 ms, walltime since start of marking 3807 ms) (average mu = 0.719, current mu = 0.116

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
Aborted (core dumped)
```

**Provide an example**
Snippet of **config.yml** 
```
connectors:
  - file: connectorRIS
    name: ris
    params:
      carefulSubscription: true
      url: ws://ris-live.ripe.net/v1/ws/
      perMessageDeflate: true
      authorizationHeader: null
      subscription:
        moreSpecific: true
        type: UPDATE
        host:
        socketOptions:
          includeRaw: false

monitors:
  - file: monitorHijack
    channel: hijack
    name: basic-hijack-detection
    params:
      thresholdMinPeers: 3

  - file: monitorNewPrefix
    channel: newprefix
    name: prefix-detection
    params:
      thresholdMinPeers: 3

  - file: monitorPath
    channel: path
    name: path-matching
    params:
      thresholdMinPeers: 1

  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection
    params:
      thresholdMinPeers: 40
      notificationIntervalSeconds: 3600

  - file: monitorAS
    channel: misconfiguration
    name: asn-monitor
    params:
      thresholdMinPeers: 3

  - file: monitorRPKI
    channel: rpki
    name: rpki-monitor
    params:
      thresholdMinPeers: 3
      checkUncovered: false
      checkDisappearing: false

  - file: monitorROAS
    channel: roa
    name: rpki-diff
    params:
      enableDiffAlerts: true
      enableExpirationAlerts: true
      enableExpirationCheckTA: true
      enableDeletedCheckTA: true
      enableAdvancedRpkiStats: false
      roaExpirationAlertHours: 2
      checkOnlyASns: true
      toleranceDeletedRoasTA: 20
      toleranceExpiredRoasTA: 20

  - file: monitorPathNeighbors
    channel: path
    name: path-neighbors
    params:
      thresholdMinPeers: 3

reports:
  - file: reportSlack
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
      - roa
    params:
      showPaths: 0 # Amount of AS_PATHs to report in the alert
      colors:
        hijack: '#d60b1c'
        newprefix: '#fa9548'
        visibility: '#fad648'
        path: '#42cbf5'
        rpki: '#d892f0'
        roa: '#d892f0'
      hooks:
        default: <my-slack-channel-uri>



############################
# Notification settings:
# - notificationIntervalSeconds
#       Defines the amount of seconds after which an alert can be repeated. An alert is repeated only if the event that
#       triggered it is not yet solved.
# - persistStatus
#       Persist the status of BGPalerter. If the process is restarted, the list of alerts already sent is recovered
#       and they are not repeated. The process must be able to write on disc, this option will create a file inside .cache/

notificationIntervalSeconds: 86400
persistStatus: true


############################
# REST API settings:
# - rest.host
#       The IP address the server will listen. The default value is localhost, this means the API will not be reachable
#       from another host. To make it public use null or 0.0.0.0.
# - rest.port
#       The port the server will listen

rest:
  host: localhost
  port: 8011

logging:
  directory: logs
  logRotatePattern: YYYY-MM-DD
  maxRetainedFiles: 10
  maxFileSizeMB: 15
  compressOnRotation: false
  useUTC: true

checkForUpdatesAtBoot: true
generatePrefixListEveryDays: 0

############################
# The files containing the monitored prefixes. Please see prefixes.yml for an example.
# This is an array (use new lines and dashes!)

monitoredPrefixesFiles:
  - prefixes.yml

############################
# RPKI settings:
# Global RPKI settings shared across all monitors requiring RPKI data
# More information here: https://github.com/nttgin/BGPalerter/blob/main/docs/rpki.md
#
# To enable ROA expiration alerts, you need VRPs including expiration timestamps.
# "rpkiclient" is the default vrpProvider since is the only one supporting ROAs expiration data.

rpki:
  vrpProvider: rpkiclient
  preCacheROAs: true
  refreshVrpListMinutes: 15
  markDataAsStaleAfterMinutes: 120


############################
# Advanced settings (Don't touch here!)
# Please, refer to the documentation to know the meaning of the following parameters.

alertOnlyOnce: false
fadeOffSeconds: 360
checkFadeOffGroupsSeconds: 30
pidFile: bgpalerter.pid
maxMessagesPerSecond: 6000
multiProcess: false
environment: production
configVersion: 2
```

prefixes.yml is auto generated using below command

`npm run generate-prefixes -- --a 8422 --o prefixes.yml`

**Expected behavior**
Expectation is bgpalerter should run with any config without any issue.

**Are you using the binary or the source code?**
docker image
