### ISSUE TITLE
AFRINIC TA malfunctions

### ISSUE THREAD

**Issue by massimocandela** [nttgin/BGPalerter#1204]
Are you receiving TA malfunctions for AFRINIC? Those alerts are correct.

See https://lists.afrinic.net/pipermail/dbwg/2023-November/000493.html

**Comment by Ferine2016** [comment]
How can we filter those alerts?

**Comment by job** [comment]
We've made a number of changes to `rpki-client` to change the response to detection of issues with inconsistent publications. This means that the issues still are happening, but that the "Possible TA Malfunction" alert will fire less often.

For a full description of the code change see this commit https://github.com/openbsd/src/commit/102443c78d43b607a4b5a168e8a80cdcdebf3e58

Note: the TA still is malfunctioning, but a TA would have to malfunction for multiple consecutive hours before this fires. The `rpki-client` code changes do not solve the underlaying problems at the TA side.

**Comment by massimocandela** [comment]
BGPalerter [v1.33.0](https://github.com/nttgin/BGPalerter/releases/tag/v1.33.0) has been released a few days ago. It includes the possibility to specify a tolerance threshold for each TA (see `toleranceDeletedRoasTA ` and `toleranceExpiredRoasTA ` [here](https://github.com/nttgin/BGPalerter/blob/main/docs/configuration.md#monitorroas)).
However, to benefit from this new feature you need to generate a new config.yml file, or manually add the tolerance values.

Suggested tolerance values are:
```yml
      toleranceDeletedRoasTA:
        ripe: 20
        apnic: 20
        arin: 20
        lacnic: 20
        afrinic: 50
      toleranceExpiredRoasTA:
        ripe: 20
        apnic: 20
        arin: 20
        lacnic: 20
        afrinic: 50
```
