### ISSUE TITLE
IPv6 prefix is configured but bgpalerter complains "is not in the configured list of announced prefixes"

### ISSUE THREAD

**Issue by zxyz** [nttgin/BGPalerter#143]
**Describe the bug**

I upgraded from 1.22.0 to 1.23.1 (binary on Debian 10), didn't change the configuration apart from the changed "processMonitors:  - file: uptimeApi" part. Now BGP alerter is not recognizing the configured IPv6 prefix anymore, the IPv4 one is fine.

Both prefixes are not RPKI signed (yes I know...the IPv4 is legacy space, the IPv6 I have to ask the sponsoring LIR to turn activate it, will do).

**Provide an example**

Error message is: 
"AS65000 is announcing 2001:db8:123::/48 but this prefix is not in the configured list of announced prefixes"

prefixes.yml:
```
'2001:db8:123::/48':
  description: No description provided
  asn:
    - 65000
  ignoreMorespecifics: false
  ignore: false
192.168.22.0/24:
  description: No description provided
  asn:
    - 65000
  ignoreMorespecifics: false
  ignore: false

options:
  monitorASns:
    6500:
      group: default
```

**Expected behavior**
Configured prefix recognized by bgpalerter

**Are you using the binary or the source code?**
binary

**Your information**
Volunteering for a non profit oriented small NGO AS where all are volunteers and noone gets any money.

Thank you!
