### ISSUE TITLE
no default group defined

### ISSUE THREAD

**Issue by pysio2007** [nttgin/BGPalerter#1490]
## Describe the bug

BGPalerter, version: 1.33.0 

LOG: 

```log
2025-06-21T06:04:21+08:00 info: Test connector connected
2025-06-21T06:04:21+08:00 error: reportHTTP is not enabled: no default group defined
```
Config: 
```yaml
reports:
  - file: reportHTTP
    params:
      templates:
        default: '{"content": "BGP Alert: ${summary}"}'
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
    isTemplateJSON: true
    method: post
    showPaths: 2
    headers:
      'Content-Type': 'application/json'
    hooks:
      default: XXXXXXXXXX
```

It seems that I have already set the default according to the documentation, but it still prompts "no default group defined."

AS210440 / Akaere Networks
