### ISSUE TITLE
possible withdrawal-detection issue

### ISSUE THREAD

**Issue by ccaputo** [nttgin/BGPalerter#255]
**Describe the bug**
While running HEAD (bcb6ba8934a978b62b6626107c0c423be7f91792), we recently had these 3 alerts:

```
A new prefix 2001:504:16::/64 is announced by AS34553. It should be instead 2001:504:16::/48 (SIX IPv6) announced by AS33108

DETAILS:
------------------------------------------------------
Monitored prefix:     2001:504:16::/48
Prefix Description:   SIX IPv6
Usually announced by: AS33108
Event type:           basic-hijack-detection
Now announced by:     AS34553
Now announced with:   2001:504:16::/64
When event started:   2020-06-07 19:56:42 UTC
Last event:           2020-06-07 19:56:42 UTC
Detected by peers:    1
See in BGPlay:
https://stat.ripe.net/widget/bgplay#w.resource=2001:504:16::/48&w.ignoreReannouncements=true&w.starttime=1591559502&w.endtime=1591559802&w.rrcs=0,1,2,5,6,7,10,11,13,14,15,16,18,20&w.type=bgp

Top 1 most used AS paths:
[]
```

```
A new prefix 2001:504:16:1::/64 is announced by AS34553. It should be instead 2001:504:16::/48 (SIX IPv6) announced by AS33108


DETAILS:
------------------------------------------------------
Monitored prefix:     2001:504:16::/48
Prefix Description:   SIX IPv6
Usually announced by: AS33108
Event type:           basic-hijack-detection
Now announced by:     AS34553
Now announced with:   2001:504:16:1::/64
When event started:   2020-06-07 19:56:42 UTC
Last event:           2020-06-07 19:56:42 UTC
Detected by peers:    1
See in BGPlay:
https://stat.ripe.net/widget/bgplay#w.resource=2001:504:16::/48&w.ignoreReannouncements=true&w.starttime=1591559502&w.endtime=1591559802&w.rrcs=0,1,2,5,6,7,10,11,13,14,15,16,18,20&w.type=bgp

Top 1 most used AS paths:
[]
```

```
A new prefix 206.81.80.0/23 is announced by AS34553. It should be instead 206.81.80.0/22 (SIX IPv4) announced by AS33108

DETAILS:
------------------------------------------------------
Monitored prefix:     206.81.80.0/22
Prefix Description:   SIX IPv4
Usually announced by: AS33108
Event type:           basic-hijack-detection
Now announced by:     AS34553
Now announced with:   206.81.80.0/23
When event started:   2020-06-07 19:57:04 UTC
Last event:           2020-06-07 19:57:04 UTC
Detected by peers:    1
See in BGPlay:
https://stat.ripe.net/widget/bgplay#w.resource=206.81.80.0/22&w.ignoreReannouncements=true&w.starttime=1591559524&w.endtime=1591559824&w.rrcs=0,1,2,5,6,7,10,11,13,14,15,16,18,20&w.type=bgp

Top 1 most used AS paths:
[]
```

This was due to a network directly peering with RIPE RIS and leaking our prefixes.  Might the direct peering with RIPE RIS explain the lack of an AS path?

Of more concern is that after the network corrected the leak, we did not receive a ```withdrawal-detection``` event, and yet viewing at https://stat.ripe.net/ confirms the withdrawals did happen.

Bug?

**Are you using the binary or the source code?**

Source code with pull up to: bcb6ba8934a978b62b6626107c0c423be7f91792

**Your information**

AS33108, SIX

**Comment by ccaputo** [comment]
To be clear, I have successfully gotten ```withdrawal-detection``` events in the past, prior to 1.25.0, so I don't know if this issue is with the novel direct RIPE RIS leak or something else.

**Comment by massimocandela** [comment]
Hi @ccaputo, 

Could you please provide me with the portion of `config.yml` where you configure the monitors?

**Comment by ccaputo** [comment]
```
monitors:
  - file: monitorHijack
    channel: hijack
    name: basic-hijack-detection
    params:
      thresholdMinPeers: 1

  - file: monitorNewPrefix
    channel: newprefix
    name: prefix-detection
    params:
      thresholdMinPeers: 1

  - file: monitorPath
    channel: path
    name: path-matching
    params:
      thresholdMinPeers: 0

  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection
    params:
      thresholdMinPeers: 1

  - file: monitorAS
    channel: misconfiguration
    name: asn-monitor
    params:
      thresholdMinPeers: 1
```

Testing previously logged a withdrawal:

```
2020-03-20T21:30:00+00:00 verbose: A new prefix 208.90.171.0/24 is announced by AS6456. It should be instead 208.90.168.0/22 (TEST Altopia IPv4 with unexpected ASN) announced by AS33108
2020-03-20T22:25:13+00:00 verbose: The prefix 208.90.168.0/22 (TEST Altopia IPv4 with unexpected ASN) it's no longer visible (withdrawn) from the peer 198.32.160.87
```

while this time, the log didn't have it:

```
2020-06-07T19:56:42+00:00 verbose: A new prefix 2001:504:16:1::/64 is announced by AS34553. It should be instead 2001:504:16::/48 (SIX IPv6) announced by AS33108
2020-06-07T19:56:42+00:00 verbose: A new prefix 2001:504:16::/64 is announced by AS34553. It should be instead 2001:504:16::/48 (SIX IPv6) announced by AS33108
2020-06-07T19:57:04+00:00 verbose: A new prefix 206.81.80.0/23 is announced by AS34553. It should be instead 206.81.80.0/22 (SIX IPv4) announced by AS33108
```

**Comment by massimocandela** [comment]
The visibility of specific BGP messages is related to their ability to change a best path with one of the RIS peers (RIS has 600+ peers worldwide). The AS hijacking your prefix is a RIS peer, and so you immediately received an alert since you have a "thresholdMinPeers" set to 1. That is correct and explains the as_path empty. I think you should increase such threshold to at least 2 peers (default value) to avoid local events which produce noise.

The `monitorVisibility` has instead a higher `thresholdMinPeers` by default, which I suggest to set to 20. 
Independently from what is the threshold, `monitorVisibility` works with exact match on the monitored prefixes. The logic behind this is "I should not trigger an alert for a prefix that has been withdrawn if this prefix was not supposed to be announced in the first place".

* So in your case: AS34553 leaks 206.81.80.0/23, `monitorHijack` triggers an alert because a more specific of `206.81.80.0/22` is received. 
* AS34553 fixes the leak
* `monitorVisibility` receives a withdraw for 206.81.80.0/23. An alert is not triggered because `206.81.80.0/23` is different from `206.81.80.0/22` and it should not have being announced in the first place.

I believe this to be a good behaviour for production monitoring.  However, are there use cases where alerting for whatever subprefix gets withdrawn is expected?

**Comment by ccaputo** [comment]
I really appreciate your support here.  Thank you.

> I think you should increase such threshold to at least 2 peers (default value) to avoid local events which produce noise.

We are an IXP and these prefixes are the peering fabric prefixes.  As such, we never want them in the global routing table, so we want to catch even the slightest (ie. >=1 peer) announcement so we can quickly reach out to a network and have it corrected.

> * are there use cases where alerting for whatever subprefix gets withdrawn is expected? (it would be easy to add such feature, but I want to better understand if there is a real use case for it)

We would love to know when an errant announcement is corrected, so we have a convenient way of verifying the network's correction.

> * would it be alerting of withdrawals of previously hijacked prefixes useful? How can we define a sensible threshold on the number of withdrawals to see if the "hijack ended"?

Tunable?  I wouldn't consider the hijack ended until the active count returns to 0.

For ```prefixes.yml``` we are using:

```
206.81.80.0/22:
  description: SIX IPv4
  asn:
    - 33108
  ignoreMorespecifics: false
  ignore: false
'2001:504:16::/48':
  description: SIX IPv6
  asn:
    - 33108
  ignoreMorespecifics: false
  ignore: false
options:
  monitorASns:
    '33108':
      group: default
```

If you have recommendations of changes I should make to that, please let me know.
