### ISSUE TITLE
BGPAlerter with historical data to replay events

### ISSUE THREAD

**Issue by vgiotsas** [nttgin/BGPalerter#299]
**Describe what you would like to achieve**
Alter the input of the connectors and instead of live monitoring, parse archived BGP data from RIPE RIS or RouteViews

**Describe why the current solution (if any) is not satisfactory**
Currently, the system appears to work only with the live RIPE RIS feed

**Provide an example**
I don't have an example but I imagine the change will be something like:

```
connectors:
  - file: connectorRouteViews
    name: rv
    params:
      carefulSubscription: true
      url: http://archive.routeviews.org/bgpdata/2020.07/UPDATES/
      perMessageDeflate: true
      subscription:
        moreSpecific: true
        type: UPDATE
        host:
        socketOptions:
          includeRaw: false

```

**Your information**
Vasileios Giotsas/Lancaster University
