### ISSUE TITLE
context is not defined - showPaths issue

### ISSUE THREAD

**Issue by mfld-pub** [nttgin/BGPalerter#302]
**Describe the bug**
I am testing the v 1.26.0 release and configured Telegram notifications and would like some clarification on the 
`chatIds:` and `default: ` options in the configuration.

**Provide an example**
 ```
 - file: reportTelegram
channels: 
- hijack
- newprefix
- visibility
- path
- misconfiguration
- rpki
params:
showPaths: 5 # Amount of AS_PATHs to report in the alert
botUrl: https://api.telegram.org/bot12345678:XXXXXXXXXXXX/sendMessage         <- Bot ID and API token. 
Validated via _getUpdates_ endpoint                                                                                                                                      
chatIds: 
default: xxxxx <- ID of the group chat that the bot and the users are in.
Bot can see messages posted there via the /getUpdates endpoint        

```
**Expected behavior**
I would expect that events are being sent to the chat ID of the default user group. In prefixes.yml I do have the monitored ASN allocated to the "default" group. 
```
options:
  monitorASns:
    '212996':
      group: default
```
E-mail alerts work OK.

I have **chatIds** blank because I just want it to send to the default group 

**Are you using the binary or the source code?**
The binary on Ubuntu 20.04 as a systemd service.

**Your information**
Michael Felden, AS212996

**Comment by massimocandela** [comment]
Hello @mfld-pub,

The error you reported in the subject makes me think the indentation of your config file is corrupted.
Could you verify that your indentation is as follows:

```
  - file: reportTelegram
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
    params:
      showPaths: 0 # Amount of AS_PATHs to report in the alert
      botUrl: https://api.telegram.org/bot<_BOT_ID_>/sendMessage
      chatIds:
        default: _CHAT_ID_
```
Indeed, the default groups is mandatory and will receive all types of alerts. The default groups must be declared inside chatIds (it is the id of the default group) and cannot be blank.
