### ISSUE TITLE
Report Channel "Elasticsearch"

### ISSUE THREAD

**Issue by cadirol** [nttgin/BGPalerter#705]
**Describe what you would like to achieve**
It would be great, if all the Report Data can sent directly to Elasticsearch. Of course, it is possible to fetch the logfile, and send all the data via local logstash instance. But direct "Link" to Elasticsearch would be great.
The BGPalerter Data in Elasticsearch would be a great place for all the SIEM aggregations! Together with Network Host Logs, BMP Data, would be a fancy solution.

**Describe why the current solution (if any) is not satisfactory**
Connect a local logstash instance to report.log, and send it to Elasticsearch

**Provide an example**
```
  - file: reportES
    channels:
      - hijack
      - ...  
    params:
      host: _ES_HOST_
      port: _PORT_
    templates:
       ...i think not needed...
```

**Your information**
Adrian - AS15576  
If Elasticsearch is not on your roadmap, i can try to contribute!
Please let me know!
