### ISSUE TITLE
Process restarts often when using systemd service.

### ISSUE THREAD

**Issue by netstx** [nttgin/BGPalerter#888]
I am not sure if this is expected behavior, so figured I'd open an issue.

**Description**
When running as a service with systemd, the bgpalerter process will restart on its own every ~10 minutes.

**Systemd service config and log example**

```
[Unit]
Description=BGPalerter
After=network.target

[Service]
Type=simple
Restart=on-failure
RestartSec=30s
User=bgpalerter
WorkingDirectory=/home/bgpalerter
ExecStart=/home/bgpalerter/bgpalerter-linux-x64

[Install]
WantedBy=multi-user.target
```

```
2022-08-15T18:01:10-05:00 info: ris connector connected (instance:6e16e20e-8c05-4830-9a57-7c37812f2bf7 connection:86cdbd2f-9b19-47e6-944c-1df3fe1c4943)
2022-08-15T18:01:10-05:00 info: Subscribed to monitored resources
2022-08-15T18:01:10-05:00 info: Subscribed to beacons
2022-08-15T18:11:55-05:00 info: ris connector connected (instance:71bd9ed3-3168-445d-98cc-59f5339a3bfb connection:414a9d8c-db8a-4257-af7a-6c2303632fc2)
2022-08-15T18:11:55-05:00 info: Subscribed to monitored resources
2022-08-15T18:11:55-05:00 info: Subscribed to beacons
2022-08-15T18:22:37-05:00 info: ris connector connected (instance:0615ac35-9864-4143-9e45-074e67f6db5e connection:a3006ae3-2473-4f35-8d0c-398e5ff23447)
2022-08-15T18:22:37-05:00 info: Subscribed to monitored resources
2022-08-15T18:22:37-05:00 info: Subscribed to beacons
```

**Expected behavior**
Process to remain running unless stopped.

**Are you using the binary or the source code?**
linux x64 binary on Debian 11

**Your information**
AS62943

**Comment by massimocandela** [comment]
Hi @netstx,

This is definitely not an expected behavior:)
According to the logs you posted, your BGPalerter process dies every 10 minutes and systemd restarts it.
It dies silently, with no error logs. This is really weird.

Basic checks:
* BGPalerter needs to write some files in the same directory where it is installed. Please, make sure there is enough space and that the process is able to write (e.g., be sure the user bgpalerter declared in systemd has the correct access right for the bgpalerter directory)
* be sure nothing is killing the process externally.

Please share your config file (be careful to remove passwords etc).

In any case, debug steps:
1) please, install this (version)[https://github.com/nttgin/BGPalerter/releases/tag/v1.30.1] (it's a pre-release). You just need to replace the binary file.
2) edit your `config.yml` and be sure to have a line `enableAdvancedRpkiStats: false` (here)[https://github.com/nttgin/BGPalerter/blob/dev/config.yml.example#L66]. This is not a solution, it's just to understand if the silent crash is somehow related to this feature. If yes, I will need to understand why.

Thanks.

**Comment by netstx** [comment]
Thanks @massimocandela!

Below is some more additional info, on my 2nd instance (same exact installation method, OS and issue described above, but using it for testing this problem):

**systemctl status bgpalerter** - note process memory usage at about 10m uptime, host has 1GB ram
```
● bgpalerter.service - BGPalerter
     Loaded: loaded (/etc/systemd/system/bgpalerter.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-08-16 05:38:29 CDT; 10min ago
   Main PID: 153278 (bgpalerter-linu)
      Tasks: 10 (limit: 1132)
     Memory: 557.9M
        CPU: 22.352s
     CGroup: /system.slice/bgpalerter.service
             └─153278 /home/bgpalerter/bgpalerter-linux-x64

Aug 16 05:38:29 vultr systemd[1]: Started BGPalerter.
Aug 16 05:38:29 vultr bgpalerter-linux-x64[153278]: Loaded config: /home/bgpalerter/config.yml
Aug 16 05:38:29 vultr bgpalerter-linux-x64[153278]: BGPalerter, version: 1.30.0 environment: production
Aug 16 05:38:41 vultr bgpalerter-linux-x64[153278]: Monitoring 192.154.3.0/24
Aug 16 05:38:41 vultr bgpalerter-linux-x64[153278]: Monitoring 2a06:a005:ae0::/44
Aug 16 05:38:41 vultr bgpalerter-linux-x64[153278]: Monitoring 2a06:1180:1::/48
Aug 16 05:38:41 vultr bgpalerter-linux-x64[153278]: Monitoring 2a06:c3c0:6::/48
Aug 16 05:38:41 vultr bgpalerter-linux-x64[153278]: Monitoring 2a06:a005:2d8::/48
Aug 16 05:38:41 vultr bgpalerter-linux-x64[153278]: Monitoring 2604:2980:f603::/48
Aug 16 05:38:41 vultr bgpalerter-linux-x64[153278]: Monitoring AS394414
```

**directory and files**
```
bgpalerter@vultr:~$ pwd
/home/bgpalerter
bgpalerter@vultr:~$ ls -lhas
total 62M
4.0K drwxr-xr-x 6 bgpalerter bgpalerter 4.0K Aug 15 18:31 .
4.0K drwxr-xr-x 3 root       root       4.0K Aug 14 21:36 ..
4.0K -rw------- 1 bgpalerter bgpalerter 1.9K Aug 15 18:30 .bash_history
4.0K -rw-r--r-- 1 bgpalerter bgpalerter  220 Aug 14 21:36 .bash_logout
4.0K -rw-r--r-- 1 bgpalerter bgpalerter 3.5K Aug 14 21:36 .bashrc
62M -rwxr-xr-x 1 bgpalerter bgpalerter  62M Aug  9 04:38 bgpalerter-linux-x64
4.0K drwxr-xr-x 2 bgpalerter bgpalerter 4.0K Aug 15 18:35 .cache
8.0K -rw-r--r-- 1 bgpalerter bgpalerter 6.0K Aug 15 18:30 config.yml
4.0K drwxr-xr-x 3 bgpalerter bgpalerter 4.0K Aug 14 21:38 .local
4.0K drwxr-xr-x 2 bgpalerter bgpalerter 4.0K Aug 16 05:49 logs
4.0K -rw-r--r-- 1 bgpalerter bgpalerter 1.2K Aug 15 15:32 prefixes.yml
4.0K -rw-r--r-- 1 bgpalerter bgpalerter  807 Aug 14 21:36 .profile
4.0K drwxr-xr-x 3 bgpalerter bgpalerter 4.0K Aug 14 21:45 src
4.0K -rw-r--r-- 1 bgpalerter bgpalerter  165 Aug 14 21:36 .wget-hsts
bgpalerter@vultr:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            472M     0  472M   0% /dev
tmpfs            98M  668K   97M   1% /run
/dev/vda1        24G  5.0G   18G  23% /
tmpfs           489M     0  489M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            98M     0   98M   0% /run/user/0
```

**config**
```
bgpalerter@vultr:~$ cat config.yml
connectors:
  - file: connectorRIS
    name: ris
    params:
      carefulSubscription: true
      url: ws://ris-live.ripe.net/v1/ws/
      perMessageDeflate: true
      authorizationHeader: null
      subscription:
        moreSpecific: true
        type: UPDATE
        host:
        socketOptions:
          includeRaw: false

#  - file: connectorRISDump
#    name: dmp

monitors:
  - file: monitorHijack
    channel: hijack
    name: basic-hijack-detection
    params:
      thresholdMinPeers: 3

  - file: monitorNewPrefix
    channel: newprefix
    name: prefix-detection
    params:
      thresholdMinPeers: 3

  - file: monitorPath
    channel: path
    name: path-matching
    params:
      thresholdMinPeers: 1

  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection
    params:
      thresholdMinPeers: 40

  - file: monitorAS
    channel: misconfiguration
    name: asn-monitor
    params:
      thresholdMinPeers: 3

  - file: monitorRPKI
    channel: rpki
    name: rpki-monitor
    params:
      thresholdMinPeers: 3
      checkUncovered: false
      checkDisappearing: false

  - file: monitorROAS
    channel: roa
    name: rpki-diff
    params:
      enableDiffAlerts: true
      enableExpirationAlerts: true
      enableExpirationCheckTA: true
      enableDeletedCheckTA: true
      roaExpirationAlertHours: 2
      checkOnlyASns: true
      toleranceDeletedRoasTA: 20
      toleranceExpiredRoasTA: 20

  - file: monitorPathNeighbors
    channel: path
    name: path-neighbors
    params:
      thresholdMinPeers: 3

reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
      - roa
    params:
      persistAlertData: false
      alertDataDirectory: alertdata/

  - file: reportEmail
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
      - roa
    params:
      showPaths: 10 # Amount of AS_PATHs to report in the alert
      senderEmail: rafael@thinkpad.io
      smtp:
        host: smtp.fastmail.com
        port: 465
        secure: true # If true the connection will use TLS when connecting to server. If false it will be still possible doing connection upgrade via STARTTLS
        ignoreTLS: false # If true TLS will be completely disabled, including STARTTLS. Set this to true if you see certificate errors in the logs.
        auth:
          user: user@email.com
          pass: password
          type: login
        tls:
          rejectUnauthorized: true  # Reject unauthorized certificates
      notifiedEmails:
        default:
          - bgpalerts@email2.net
        noc:
          - bgpalerts@email2.net

############################
# Notification settings:
# - notificationIntervalSeconds
#       Defines the amount of seconds after which an alert can be repeated. An alert is repeated only if the event that
#       triggered it is not yet solved.
# - persistStatus
#       Persist the status of BGPalerter. If the process is restarted, the list of alerts already sent is recovered
#       and they are not repeated. The process must be able to write on disc, this option will create a file inside .cache/

notificationIntervalSeconds: 3600
persistStatus: true


############################
# REST API settings:
# - rest.host
#       The IP address the server will listen. The default value is localhost, this means the API will not be reachable
#       from another host. To make it public use null or 0.0.0.0.
# - rest.port
#       The port the server will listen

rest:
  host: localhost
  port: 8011

logging:
  directory: logs
  logRotatePattern: MM-DD-YYYY
  maxRetainedFiles: 10
  maxFileSizeMB: 15
  compressOnRotation: false
  useUTC: false

checkForUpdatesAtBoot: false
generatePrefixListEveryDays: 1

############################
# Process monitoring settings:
# Uncomment or add classes under processMonitors if you want to monitor or send logs about the status of the BGPalerter process

processMonitors:
#  - file: uptimeApi
#    params:
#      useStatusCodes: true
#
  - file: uptimeHealthcheck
    params:
      url: https://hc-ping.com/9df2b8a9-d2bf-4894-ad68-a849ce8de3e0
      intervalSeconds: 60
      method: get
#
#  - file: sentryModule
#    params:
#      dsn: https://<key>@sentry.io/<project>


############################
# The files containing the monitored prefixes. Please see prefixes.yml for an example.
# This is an array (use new lines and dashes!)

monitoredPrefixesFiles:
  - prefixes.yml

############################
# The file containing the user groups.
# User groups can be specified
# 1) directly above, in each report module; or
# 2) inside an external file, as specified below (disabled by default).
# Using an external file allows BGPalerter to auto-reload the user group definitions
# when the external file is changed.

# groupsFile: groups.yml.example

############################
# HTTP proxy setting:
# Allow to run BGPalerter behind an HTTP/HTTPS proxy.
# You can also specify which module can bypass the proxy.
# More information here: https://github.com/nttgin/BGPalerter/blob/main/docs/http-proxy.md

# httpProxy: http://username:password@127.0.0.1:9000


############################
# RPKI settings:
# Global RPKI settings shared across all monitors requiring RPKI data
# More information here: https://github.com/nttgin/BGPalerter/blob/main/docs/rpki.md
#
# To enable ROA expiration alerts, you need VRPs including expiration timestamps.
# "rpkiclient" is the default vrpProvider since is the only one supporting ROAs expiration data.

rpki:
  vrpProvider: rpkiclient
  preCacheROAs: true
  refreshVrpListMinutes: 15
  markDataAsStaleAfterMinutes: 120


############################
# Advanced settings (Don't touch here!)
# Please, refer to the documentation to know the meaning of the following parameters.

alertOnlyOnce: false
fadeOffSeconds: 360
checkFadeOffGroupsSeconds: 30
pidFile: bgpalerter.pid
maxMessagesPerSecond: 6000
multiProcess: false
environment: production
configVersion: 2

```

**prefixes.yml**
```
bgpalerter@vultr:~$ cat prefixes.yml
192.154.3.0/24:
  description: No description provided
  asn:
    - 394414
  ignoreMorespecifics: false
  ignore: false
  group: noc
2604:2980:f603::/48:
  description: No description provided (No ROA available)
  asn:
    - 394414
  ignoreMorespecifics: false
  ignore: false
  group: noc
2a06:a005:2d8::/48:
  description: No description provided
  asn:
    - 394414
  ignoreMorespecifics: false
  ignore: false
  group: noc
2a06:a005:ae0::/44:
  description: No description provided
  asn:
    - 394414
  ignoreMorespecifics: false
  ignore: false
  group: noc
2a06:c3c0:6::/48:
  description: No description provided
  asn:
    - 394414
  ignoreMorespecifics: false
  ignore: false
  group: noc
2a06:1180:1::/48:
  description: No description provided
  asn:
    - 394414
  ignoreMorespecifics: false
  ignore: false
  group: noc
options:
  monitorASns:
    '394414':
      group: noc
      upstreams:
        - 32621
        - 44570
        - 50058
        - 62943
        - 6939
      downstreams:
        - 968
  generate:
    exclude: []
    excludeDelegated: true
    monitoredASes:
      - '394414'
    historical: false
    group: noc
    asnList:
      - '394414'
```

I don't see a directory 'alertdata' created when running the binary for the first time... Is it required? It's on the config.

There's nothing else installed on this VM (as well as on the container that's running my production alerter for AS62943). Essentially it's a fresh Debian 11 install with just some apt packages (wget, curl, whois, net-tools, dnsutils, mtr-tiny, etc).

I am going to perform the 2 debug steps you shared above, and reply back here in an hour or two with updates. Thanks again, really appreciate it!
