### ISSUE TITLE
Make method a configurable option (reportHTTP)

### ISSUE THREAD

**Issue by nickbouwhuis** [nttgin/BGPalerter#915]
**Describe what you would like to achieve**
I would like to be able to configure the HTTP method that the reportHTTP alert module uses. At the moment, this is hardcoded to be 'POST'. Making it incompatible with APIs that use other methods for messages (for example: Matrix uses 'PUT' requests for sending messages to rooms).

**Describe why the current solution (if any) is not satisfactory**
The current situation makes the module incompatible with APIs that do not use the 'POST' method. 

**Provide an example**
For Matrix, the config.yml would look something like this:
```yml
  - file: reportHTTP
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
      - roa
    params:
      templates: 
        default: '{"body": "${channel}: ${summary}", "msgtype": "m.text"}'
      headers:
      isTemplateJSON: true
      showPaths: 0
      method: 'PUT'
      hooks:
        default: https://HOMESERVER/_matrix/client/v3/rooms/CHANNELID/send/m.room.message/?access_token=TOKEN
```

**Your information**
By day:
Nick Bouwhuis
Speakup B.V.
AS49627

By night:
Nick Bouwhuis
AS202585
