### ISSUE TITLE
Telegram report does not work

### ISSUE THREAD

**Issue by marek22k** [nttgin/BGPalerter#919]
**Describe the bug**
I have set up Telegram - as per the instructions. However, it does not work. I then created a test server and put the API endpoint there and instead of getting a post request with parameters, I got a post request with JSON. Maybe they forgot to convert the JSON to a post request?

**Provide an example**
```
  - file: reportTelegram
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
      - roa
    params:
      showPaths: 0 # Amount of AS_PATHs to report in the alert
      botUrl: https://api.telegram.org/botID:KEY/
      chatIds:
        default: XXXX
```

**Expected behavior**
I get a message via Telegram. BgpAlerter makes a post request with post parameters, no JSON string.

**Are you using the binary or the source code?**
The binary from GitHub.

**Your information**
Got
```
POST /botXXX/ HTTP/1.1
User-Agent: ntt-bgpalerter/1.30.1
Content-Type: application/json
Content-Length: 211
Host: 127.0.0.1:1234
Connection: close

{"chat_id":XXX,"text":"type:announcement timestamp:1665041193945 prefix:193.0.0.0/21 peer:1.2.3.5 path:[1,2,3,3333] nextHop:1.2.3.4 aggregator:null","parse_mode":"markdown","disable_web_page_preview":true}
```
but except
```
POST /botXXX/ HTTP/1.1
User-Agent: ntt-bgpalerter/1.30.1
Content-Type: application/json
Content-Length: 211
Host: 127.0.0.1:1234
Connection: close

chat_id=XXX&text=type:announcement ...
```
