### ISSUE TITLE
Some BPG IPv6 withdrawal events no longer register. RPKI ROA events and IPv4 withdrawal events are detected correctly.

### ISSUE THREAD

**Issue by mfld-pub** [nttgin/BGPalerter#993]
**Describe the bug**
Two prod instances at two different vantage points are configured to report on withdrawal events, hijacks, unexpected prefixes from the ASN. Since upgrading, these events do not register. Notifications are not triggered and nothing is in reports.log

**Provide an example**
As the prod instances have convoluted yml that have survived years of version upgrade I deployed a brand new Debian 11 instance and started from scratch for testing.

- AS212996 is announcing 2a0c:9a40:8d60::/44
- Install the [latest version ](https://github.com/nttgin/BGPalerter/releases/download/v1.31.0/bgpalerter-linux-x64) on a new Debian 11 instance that has dual stack connectivity and no egress firewall.
- Run the onboarding. `chmod +x bgpalerter-linux-x64 && ./bgpalerter-linux-x64`
- Wait for it to confirm it is running:

![Screenshot 2022-12-21 164712](https://user-images.githubusercontent.com/66289900/208959406-37050dac-d88c-455d-be2b-a581d4c5da36.png)

- In ./logs I monitor errors and reports `tail -f reports.log` ,  `tail -f errors.log`
- Open a RISlive connection and subscribe for updates filtering for the ASN
```
// Received at 16:52:19
{
    "type": "ris_subscribe_ok",
    "data": {"subscription":{"host":"rrc04.ripe.net","path":"212996$"},"socketOptions":{"includeRaw":false,"acknowledge":true}}
}
```

- Withdraw the prefix and wait.
- See the withdrawal in RISlive
- See no activity in reports.log. error.log just shows subscription to RIS when I started the process:
```
2022-12-21T16:46:15+00:00 info: ris connector connected (instance:e147e27a-7a8d-408b-9255-e07299794665 connection:5204c8fb-0ada-45ad-90bb-dca42549ae81)
2022-12-21T16:46:15+00:00 info: Subscribed to monitored resources
2022-12-21T16:46:15+00:00 info: Subscribed to monitored resources
2022-12-21T16:46:15+00:00 info: Subscribed to beacons
2022-12-21T16:46:15+00:00 info: Subscribed to beacons
2022-12-21T16:46:15+00:00 info: Prefix rules reloaded
```

What I have done to troubleshoot:

- Deploy new on dev instance
- Set thresholdMinPeers: 5 for withdrawal-detection in config.xml 
```
  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection
    params:
      thresholdMinPeers: 5
```

**Expected behavior**
withdrawal-detection should have triggered and logged to reports.log once I could see the prefix gone in RISlive

**Are you using the binary or the source code?**
linux-64 binary

**Your information**
Michael Felden, AS212996

**Comment by mfld-pub** [comment]
FWIW if I empty out the auto generated prefixes.yml to just monitor the ASN, it does detect announcements so its clearly talking to the RIS and able to write to reports.log

```
options:
  monitorASns:
    '212996':
      group: noc
      upstreams:
        - 20473
        - 34927
      downstreams: []
  generate:
    exclude: []
    excludeDelegated: true
    monitoredASes:
      - '212996'
    historical: false
    group: noc
    asnList:
      - '212996'
```

`2022-12-21T17:12:51+00:00 verbose: AS212996 is announcing 2a0c:9a40:8d60::/44 but this prefix is not in the configured list of announced prefixes` 

Just withdrawal events (and maybe other events) of known prefixes seem to be ignored.

**Comment by massimocandela** [comment]
Hi @mfld-pub, can you provide me with a utc timestamp of when you attempted the withdrawal of the prefix? Please, provide me with an attempt older than 2 hours if available.

**Comment by massimocandela** [comment]
Also, if you can attach the prefixes.yml you used for the experiment and the config.yml stripped out of passwords and other chat configuration. Feel free to send it by email.

**Comment by mfld-pub** [comment]
> Also, if you can attach the prefixes.yml you used for the experiment and the config.yml stripped out of passwords and other chat configuration. Feel free to send it by email.

Sure thing. The config.xml is not sensitive as I did an install from scratch for this and there is only reporting to log file enabled on this dev instance. have attached them here in D.zip

I did uncomment 

```
  - file: monitorNewPrefix
    channel: newprefix
    name: prefix-detection
    params:
      thresholdMinPeers: 3
```

and I did set thresholdMinPeers: 3 for channel: visibility to make it super sensitive for testing purposes.

```
  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection
    params:
      thresholdMinPeers: 3
```

The prefixes.yml are the auto generated kind you get from initial run. The test prefix is in there.

An example where I withdrew test prefix 2a0c:9a40:8d60::/44 can be seen in RIPEstat (in UTC):

```
From 2022-12-21 14:53 to 2022-12-21 14:54

2a0c:9a40:8d60::/44	W		[152.89.170.244](https://stat.ripe.net/app/launchpad/152.89.170.244)	25
2a0c:9a40:8d60::/44	W		[2a05:4140:3::476](https://stat.ripe.net/app/launchpad/2a05:4140:3::476)	25
```

The two config files:

[D.zip](https://github.com/nttgin/BGPalerter/files/10280248/D.zip)
